development:
  adapter: postgresql
  encoding: unicode
  database: react_rails_development
  pool: 5
  username: postgres
  password: password
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: react_rails_test
  pool: 5
  username: postgres
  password: password
  port: 5432